# Changes on master have passed CI tests.
# When the CHANGELOG.md files contains no UNRELEASED changes, the commit is
# considered a published as GitHub Release and propagated to the
# deployment_trigger_repo.
# Otherwise the commit is suggested as release candidate Pull-Request.

name: 'Pull-Request Approval'
on:
  pull_request:
    branches:
      - master
    # ignore PR unless only CHANGELOG.md and VERSION have changed
    paths-ignore:
      - '*'
      - '!CHANGELOG.md'
      - '!VERSION'
    types: [opened, edited, synchronize, reopened]
jobs:
  approve:
    name: "Approve Pull-Request"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Approve Release Pull-Request
      if: github.event.sender.login == 'github-actions'
      run: |
        if [ $(git cherry ${{ github.event.pull_request.base.sha }} | wc -l) -eq 1 ]; then
          echo "Commit Distance OK";
        else 
          echo "Only 1 commit allowed.";
          exit 1;
        fi

        curl -s "${{ github.event.pull_request.url }}/reviews" \
          -H "Content-Type: application/vnd.github.v3.raw+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{ \"commit_id\": \"$(git rev-parse --verify HEAD)\", \"event\": \"APPROVE\" }"
