name: 'Main Workflow'
on: [push]
jobs:
  checks:
    name: 'Check Code Style'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.X'
    - run: python -m ensurepip
    - run: python -m pip install pytest pytest-benchmark
    - run: python -m pytest
  sdist:
    name: "Bundle Distribution"
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build the Distribution"
  deploy:
    name: "Deploy Release"
    runs-on: ubuntu-latest
    needs: [checks, sdist]
    steps:
    - run: echo "Upload the Distribution"
