name: 'branch'
on:
  push:
    branches-ignore:
      - master
env:
  module_name: "freebsd-sysctl"
  PYTHON_MODULE_NAME: "freebsd_sysctl"
jobs:
  checks:
    name: "Code Style"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.X"
    - run: python -m ensurepip
    - run: python -m pip install -U -r requirements-dev.txt
    - run: python -m flake8 --version
    - run: python -m mypy --version
    - run: python -m flake8 --exclude=".travis,.github,.eggs,__init__.py,tests"
    - run: python -m bandit --skip B404,B110 --exclude tests/ --exclude .github/ *.py "${{ env.PYTHON_MODULE_NAME }}/*.py"
  sdist:
    name: "Bundle Distribution"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.X"

    - name: Get Version
      id: get_version
      run: |
        echo ::set-output name=NAME::$(python setup.py --name)
        echo ::set-output name=VERSION::$(python setup.py --version)
    
    - name: Bundle Source Distribution
      run: python setup.py sdist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "${{ steps.get_version.outputs.NAME }}-${{ steps.get_version.outputs.VERSION }}.tar.gz"
        path: "dist/${{ steps.get_version.outputs.NAME }}-${{ steps.get_version.outputs.VERSION }}.tar.gz"
        description: "${{ steps.get_version.outputs.NAME }} v${{ steps.get_version.outputs.VERSION }}"
